### PR TITLE
Reduce terminal for function commands.

### PR DESCRIPTION
**Pull request by sudhirverma**

### CODE REVIEW

**Review by lstocchi — CHANGES_REQUESTED** [review]
Not working for me. It doesn't find `func` apparently

image

**Comment by lstocchi** [comment]
Can you please add a gif of it working? I remember you had a different ui compared to me. Maybe because the task doesn't start for me :man_shrugging: Which vscode version are you using?

**Comment by sudhirverma** [comment]
Adding video


https://user-images.githubusercontent.com/9924513/170990676-77d124d7-394f-43e2-8814-42ae6a84a643.mov

**Comment by sudhirverma** [comment]
> Can you please add a gif of it working? I remember you had a different ui compared to me. Maybe because the task doesn't start for me 🤷‍♂️ Which vscode version are you using?

My VSCode version is `1.67.2`

**Review by lstocchi — CHANGES_REQUESTED** [review]
Playing with it. What i noticed so far

1) If i have only one function opened locally the title of the terminal only shows `run Task`. I think it would be great to always see the function name as the user can open a new function in the workspace at any time.
image

2) The build action should run with the verbose flag `-v`

3) If i don't have any terminal opened and i run `Run` (actually build+run), a terminal tab called `build` is created. Then this is renamed `run` and the run action is executed here. Why doesn't it create a new terminal tab for the run action? The problem is that, if i re-run the build+run action, it creates a new terminal tab for `build` and the `run` action is executed in the old tab. So all logs are messed up.

4) Similar to the previous point. Let's say i have 2 functions (f1 and f2). First i build f1. After a while (1 min) i build f2. The terminal tab which contain the f1 logs is renamed and used to build f2. Can this be prevented? 

In the image below i first built `testmodule3` and then `testmodule4` in the same tab
image

5) The terminate/restart run task doesn't actually work. If you check the container list you will see that a new container is created but the old one is not terminated. You should send a SIGINT or SIGTERM to the process. Not sure what vscode does when you ask to terminate/restart a task
```
[luca@localhost ~]$ docker container ls
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                                                                                                                  NAMES
47afc100fb98        quay.io/lstocchi/testmodule3:latest   "/cnb/process/web"       2 minutes ago       Up 2 minutes        127.0.0.1:34701->8080/tcp                                                                                                              wizardly_lamarr
031f665dcdd5        quay.io/lstocchi/testmodule3:latest   "/cnb/process/web"       2 minutes ago       Up 2 minutes        127.0.0.1:42385->8080/tcp                                                                                                              relaxed_moore
```

**Comment by sudhirverma** [comment]
> 1. If i have only one function opened locally the title of the terminal only shows `run Task`. I think it would be great to always see the function name as the user can open a new function in the workspace at any time.


I can show the function name but in the warning message it will look like `function: build (test-1) (test-1)`. function name will come twice.

Screenshot 2022-05-30 at 11 36 41 PM


> 3\. If i don't have any terminal opened and i run `Run` (actually build+run), a terminal tab called `build` is created. Then this is renamed `run` and the run action is executed here. Why doesn't it create a new terminal tab for the run action? The problem is that, if i re-run the build+run action, it creates a new terminal tab for `build` and the `run` action is executed in the old tab. So all logs are messed up.

In the terminal, it says `press any key to close it otherwise it will be reused by task`

Screenshot 2022-05-30 at 11 40 51 PM


> 5\. The terminate/restart run task doesn't actually work. If you check the container list you will see that a new container is created but the old one is not terminated. You should send a SIGINT or SIGTERM to the process. Not sure what vscode does when you ask to terminate/restart a task

terminate/restart it's terminate and restart the terminal but it doesn’t stop the container I need to check if Task Provide an option to terminate the whole `run command` not just terminate the terminal.

**Comment by mohitsuman** [comment]
@sudhirverma Do we need this PR anymore ?

**Comment by sudhirverma** [comment]
> @sudhirverma Do we need this PR anymore ?

No, we can close this PR

**Pull request closed without merging**
