### PR TITLE
Add validation for showInputBox for service.

### LINKED ISSUE #154: Add validation for showInputBox.
When I provide the name starting with upper-case for the service it fails to Add service. 

error:

`
undefinedError: Service.serving.knative.dev "knative-tutorial-greeter:quarkus" is invalid: metadata.name: Invalid value: "knative-tutorial-greeter:quarkus": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
`

### PR DESCRIPTION
**Pull request by sudhirverma**
Fix: #154

### CODE REVIEW

**Review by lstocchi — COMMENTED** [review]
Not sure what to comment honestly as i don't have a solution. 
The code looks good but it only works in some cases. If i use a different kubernetes/knative environment (older versions, maybe newer in future) it could have another regex rule and the validation made is wrong.

E.g

image

If i type `9--test` your validation doesn't show any error but then i face the above one.

Maybe in the client we should be less strict as the backend should do the job. Just check if there are all lowercases, avoid special characters or something like that. 
It would be great if you could perform the call and show the error with the quickpick still opened so it can be updated without restarting all steps again.
Unfortunately there is no `--dry-run` option for this command so I don't know how to make it more elegant. If we merge this i'm afraid we don't solve the issue and maybe we make it worst. If you don't see any validation but the final error it's ok, you understand that the validation is made after. If you see some active validation and then an error pop up later you think "WTF?! you validate it and now it's not valid?".

@mohitsuman ideas?

**Comment by mohitsuman** [comment]
Does knative cli have any validation in place for the service name? To start I think having the minimum validation would be important.

**Comment by sudhirverma** [comment]
I have updated the regex which will validate the name with lower case alphanumeric characters

**Review by lstocchi — APPROVED** [review]
Still think this could lead to problems but if you want to have some validation it looks good with the current knative versions

**Pull request merged**
