### PR TITLE
Knative Service icon could contain a Knative logo.

### LINKED ISSUE #196: Knative Service icon could contain a Knative logo.
At the moment Knative Service logo in the VScode View is an image of wheels/gear.
logo1
Would be nice if the logo for the Service conatins actual Knative logo, as it is for example currently done in the OpenShift Developer view:
ocp
Or the current namespace icon in Knative Functions Plugin:
Snímek obrazovky 2022-03-11 v 16 22 41

### PR DESCRIPTION
**Pull request by sudhirverma**
Fix: #196

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]

**Comment by lstocchi** [comment]
Adding a comment on the issue, wait a sec before merging it please

**Review by lstocchi — COMMENTED** [review]
Not sure if this can be made but it would be better if icons could be a bit bigger. 
I have glasses so maybe this is my problem :laughing:  but i really don't see any difference if i sit normally in front of my screen. I need to get closer to read what's inside the labels.
image


Then maybe you can think about adding icons to the categories as well, as we do with tekton. Now there are folder icons. But this is your or Mohit choice
image

**Comment by mohitsuman** [comment]
@sudhirverma Can you paste the latest icon size and how it looks ?

**Comment by mohitsuman** [comment]
@sudhirverma please add the latest image after the fixes in the icon size.

**Comment by sudhirverma** [comment]
@mohitsuman below Icon with SVG

Screenshot 2022-04-04 at 5 12 00 PM

and below icon with png

Screenshot 2022-04-04 at 5 22 55 PM

**Comment by lstocchi** [comment]
> 

Maybe better with SVG. They don't look very nice but i guess vscode doesn't allow to have bigger icons?? What i really don't like (even in IJ) is the different style between the namespace icon and the rest. 

BTW I am not even sure we are doing the right thing about removing the old icons.... Joshua did great from my pov.

**Comment by mohitsuman** [comment]
Looking at the limitation we have on vscode regarding icon size and how four character string inside a badge does not align with the UI, we are not going to merge these changes. We will be using the same set of icons used by Knative service, eventing and broker as it was approved by knative upstream community.

**Pull request closed without merging**
